export default {
  category: [{
    categorySeq: 34,
    kind: "INCOME",
    name: "근로소득",
    parentSeq: 0,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 35,
    kind: "INCOME",
    name: "급여",
    parentSeq: 34,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 36,
    kind: "INCOME",
    name: "상여금",
    parentSeq: 34,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 37,
    kind: "INCOME",
    name: "수당",
    parentSeq: 34,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 38,
    kind: "INCOME",
    name: "성과급",
    parentSeq: 34,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 39,
    kind: "INCOME",
    name: "기타근로소득",
    parentSeq: 34,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 40,
    kind: "INCOME",
    name: "금융소득",
    parentSeq: 0,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 41,
    kind: "INCOME",
    name: "이자소득",
    parentSeq: 40,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 42,
    kind: "INCOME",
    name: "배당금",
    parentSeq: 40,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 43,
    kind: "INCOME",
    name: "매도차익",
    parentSeq: 40,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 44,
    kind: "INCOME",
    name: "기타금융소득",
    parentSeq: 40,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 45,
    kind: "INCOME",
    name: "기타소득",
    parentSeq: 0,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 46,
    kind: "INCOME",
    name: "퇴직금",
    parentSeq: 45,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 47,
    kind: "INCOME",
    name: "연금",
    parentSeq: 45,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 48,
    kind: "INCOME",
    name: "부업소득",
    parentSeq: 45,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 49,
    kind: "INCOME",
    name: "기타소득",
    parentSeq: 45,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 50,
    kind: "TRANSFER",
    name: "대체거래",
    parentSeq: 0,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 51,
    kind: "TRANSFER",
    name: "계좌이체",
    parentSeq: 50,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 52,
    kind: "TRANSFER",
    name: "인출",
    parentSeq: 50,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 53,
    kind: "TRANSFER",
    name: "입금",
    parentSeq: 50,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 54,
    kind: "TRANSFER",
    name: "카드결재",
    parentSeq: 50,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 55,
    kind: "TRANSFER",
    name: "현금서비스",
    parentSeq: 50,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 56,
    kind: "TRANSFER",
    name: "적금불입",
    parentSeq: 50,
    orderNo: 7,
    deleteF: false,
  },
  {
    categorySeq: 57,
    kind: "TRANSFER",
    name: "펀드불입",
    parentSeq: 50,
    orderNo: 8,
    deleteF: false,
  },
  {
    categorySeq: 58,
    kind: "TRANSFER",
    name: "기타대체거래",
    parentSeq: 50,
    orderNo: 9,
    deleteF: false,
  },
  {
    categorySeq: 59,
    kind: "SPENDING",
    name: "식료품비",
    parentSeq: 0,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 60,
    kind: "SPENDING",
    name: "주식/부식",
    parentSeq: 59,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 61,
    kind: "SPENDING",
    name: "외식",
    parentSeq: 59,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 62,
    kind: "SPENDING",
    name: "간식",
    parentSeq: 59,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 63,
    kind: "SPENDING",
    name: "아침대용",
    parentSeq: 59,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 64,
    kind: "SPENDING",
    name: "주거비",
    parentSeq: 0,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 65,
    kind: "SPENDING",
    name: "월세",
    parentSeq: 64,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 66,
    kind: "SPENDING",
    name: "주택수리비",
    parentSeq: 64,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 67,
    kind: "SPENDING",
    name: "관리비",
    parentSeq: 64,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 68,
    kind: "SPENDING",
    name: "수도료",
    parentSeq: 64,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 69,
    kind: "SPENDING",
    name: "전기료",
    parentSeq: 64,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 70,
    kind: "SPENDING",
    name: "가스비",
    parentSeq: 64,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 71,
    kind: "SPENDING",
    name: "난방비",
    parentSeq: 64,
    orderNo: 6,
    deleteF: false,
  },
  {
    categorySeq: 72,
    kind: "SPENDING",
    name: "생활용품비",
    parentSeq: 0,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 73,
    kind: "SPENDING",
    name: "가구",
    parentSeq: 72,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 74,
    kind: "SPENDING",
    name: "가전용품",
    parentSeq: 72,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 75,
    kind: "SPENDING",
    name: "주방용품",
    parentSeq: 72,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 76,
    kind: "SPENDING",
    name: "잡화/소모품",
    parentSeq: 72,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 77,
    kind: "SPENDING",
    name: "의복비",
    parentSeq: 0,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 78,
    kind: "SPENDING",
    name: "의류",
    parentSeq: 77,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 79,
    kind: "SPENDING",
    name: "신발",
    parentSeq: 77,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 80,
    kind: "SPENDING",
    name: "세탁비",
    parentSeq: 77,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 81,
    kind: "SPENDING",
    name: "이발",
    parentSeq: 77,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 82,
    kind: "SPENDING",
    name: "의료비",
    parentSeq: 0,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 83,
    kind: "SPENDING",
    name: "약값",
    parentSeq: 82,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 84,
    kind: "SPENDING",
    name: "병원비",
    parentSeq: 82,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 85,
    kind: "SPENDING",
    name: "교육비",
    parentSeq: 0,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 86,
    kind: "SPENDING",
    name: "등록금",
    parentSeq: 85,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 87,
    kind: "SPENDING",
    name: "교재비",
    parentSeq: 85,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 88,
    kind: "SPENDING",
    name: "학원비",
    parentSeq: 85,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 89,
    kind: "SPENDING",
    name: "과외비",
    parentSeq: 85,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 90,
    kind: "SPENDING",
    name: "학용품",
    parentSeq: 85,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 91,
    kind: "SPENDING",
    name: "기타교육비",
    parentSeq: 85,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 92,
    kind: "SPENDING",
    name: "문화생활비",
    parentSeq: 0,
    orderNo: 6,
    deleteF: false,
  },
  {
    categorySeq: 93,
    kind: "SPENDING",
    name: "신문도서",
    parentSeq: 92,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 94,
    kind: "SPENDING",
    name: "영화공연관람",
    parentSeq: 92,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 95,
    kind: "SPENDING",
    name: "여행",
    parentSeq: 92,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 96,
    kind: "SPENDING",
    name: "레져",
    parentSeq: 92,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 97,
    kind: "SPENDING",
    name: "기타문화생활비",
    parentSeq: 92,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 98,
    kind: "SPENDING",
    name: "교통비",
    parentSeq: 0,
    orderNo: 7,
    deleteF: false,
  },
  {
    categorySeq: 99,
    kind: "SPENDING",
    name: "주유비",
    parentSeq: 98,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 100,
    kind: "SPENDING",
    name: "대중교통비",
    parentSeq: 98,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 101,
    kind: "SPENDING",
    name: "자동체수리비",
    parentSeq: 98,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 102,
    kind: "SPENDING",
    name: "세차비",
    parentSeq: 98,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 103,
    kind: "SPENDING",
    name: "기타교통비",
    parentSeq: 98,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 104,
    kind: "SPENDING",
    name: "통신비",
    parentSeq: 0,
    orderNo: 8,
    deleteF: false,
  },
  {
    categorySeq: 105,
    kind: "SPENDING",
    name: "전화",
    parentSeq: 104,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 106,
    kind: "SPENDING",
    name: "이동전화",
    parentSeq: 104,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 107,
    kind: "SPENDING",
    name: "인터넷서비스",
    parentSeq: 104,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 108,
    kind: "SPENDING",
    name: "기타통신비",
    parentSeq: 104,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 109,
    kind: "SPENDING",
    name: "세금",
    parentSeq: 0,
    orderNo: 9,
    deleteF: false,
  },
  {
    categorySeq: 110,
    kind: "SPENDING",
    name: "소득세",
    parentSeq: 109,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 111,
    kind: "SPENDING",
    name: "재산세",
    parentSeq: 109,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 112,
    kind: "SPENDING",
    name: "자동차세",
    parentSeq: 109,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 113,
    kind: "SPENDING",
    name: "기타세금",
    parentSeq: 109,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 114,
    kind: "SPENDING",
    name: "보험료",
    parentSeq: 0,
    orderNo: 10,
    deleteF: false,
  },
  {
    categorySeq: 115,
    kind: "SPENDING",
    name: "생명보험료",
    parentSeq: 114,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 116,
    kind: "SPENDING",
    name: "자동차보험료",
    parentSeq: 114,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 117,
    kind: "SPENDING",
    name: "연금보험료",
    parentSeq: 114,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 118,
    kind: "SPENDING",
    name: "국민건강보험료",
    parentSeq: 114,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 119,
    kind: "SPENDING",
    name: "종합/정기보험",
    parentSeq: 114,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 120,
    kind: "SPENDING",
    name: "기타보험료",
    parentSeq: 114,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 121,
    kind: "SPENDING",
    name: "경조사/회비",
    parentSeq: 0,
    orderNo: 11,
    deleteF: false,
  },
  {
    categorySeq: 122,
    kind: "SPENDING",
    name: "축의금",
    parentSeq: 121,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 123,
    kind: "SPENDING",
    name: "부의금",
    parentSeq: 121,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 124,
    kind: "SPENDING",
    name: "모임회비",
    parentSeq: 121,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 125,
    kind: "SPENDING",
    name: "기타경조사/회비",
    parentSeq: 121,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 126,
    kind: "SPENDING",
    name: "기타소비지출",
    parentSeq: 0,
    orderNo: 12,
    deleteF: false,
  },
  {
    categorySeq: 127,
    kind: "SPENDING",
    name: "담배/술",
    parentSeq: 126,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 128,
    kind: "SPENDING",
    name: "화장품비",
    parentSeq: 126,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 129,
    kind: "SPENDING",
    name: "용돈",
    parentSeq: 126,
    orderNo: 2,
    deleteF: false,
  },
  {
    categorySeq: 130,
    kind: "SPENDING",
    name: "기타소비지출",
    parentSeq: 126,
    orderNo: 3,
    deleteF: false,
  },
  {
    categorySeq: 131,
    kind: "TRANSFER",
    name: "보험",
    parentSeq: 50,
    orderNo: 8,
    deleteF: false,
  },
  {
    categorySeq: 132,
    kind: "SPENDING",
    name: "기부",
    parentSeq: 121,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 133,
    kind: "SPENDING",
    name: "빌려준돈",
    parentSeq: 121,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 134,
    kind: "SPENDING",
    name: "계약금",
    parentSeq: 64,
    orderNo: 7,
    deleteF: false,
  },
  {
    categorySeq: 135,
    kind: "INCOME",
    name: "실업수당",
    parentSeq: 34,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 136,
    kind: "SPENDING",
    name: "의료실비",
    parentSeq: 114,
    orderNo: 6,
    deleteF: false,
  },
  {
    categorySeq: 138,
    kind: "INCOME",
    name: "받은돈",
    parentSeq: 45,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 139,
    kind: "SPENDING",
    name: "기타",
    parentSeq: 77,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 140,
    kind: "SPENDING",
    name: "입력누락",
    parentSeq: 0,
    orderNo: 13,
    deleteF: false,
  },
  {
    categorySeq: 141,
    kind: "SPENDING",
    name: "입력누락",
    parentSeq: 140,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 142,
    kind: "INCOME",
    name: "이자일괄 입력",
    parentSeq: 40,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 143,
    kind: "SPENDING",
    name: "부동산 중계수수료",
    parentSeq: 64,
    orderNo: 8,
    deleteF: false,
  },
  {
    categorySeq: 144,
    kind: "SPENDING",
    name: "침구류",
    parentSeq: 72,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 145,
    kind: "SPENDING",
    name: "기타",
    parentSeq: 72,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 146,
    kind: "SPENDING",
    name: "기타",
    parentSeq: 64,
    orderNo: 9,
    deleteF: false,
  },
  {
    categorySeq: 147,
    kind: "SPENDING",
    name: "스포츠",
    parentSeq: 92,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 148,
    kind: "SPENDING",
    name: "선물",
    parentSeq: 121,
    orderNo: 6,
    deleteF: false,
  },
  {
    categorySeq: 149,
    kind: "SPENDING",
    name: "택배",
    parentSeq: 104,
    orderNo: 4,
    deleteF: false,
  },
  {
    categorySeq: 150,
    kind: "INCOME",
    name: "보험금",
    parentSeq: 45,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 151,
    kind: "SPENDING",
    name: "통행료",
    parentSeq: 98,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 152,
    kind: "SPENDING",
    name: "기타 지출",
    parentSeq: 0,
    orderNo: 14,
    deleteF: false,
  },
  {
    categorySeq: 153,
    kind: "SPENDING",
    name: "스톡옵션매입",
    parentSeq: 152,
    orderNo: 0,
    deleteF: false,
  },
  {
    categorySeq: 154,
    kind: "SPENDING",
    name: "서류발급",
    parentSeq: 126,
    orderNo: 5,
    deleteF: false,
  },
  {
    categorySeq: 155,
    kind: "SPENDING",
    name: "상품권",
    parentSeq: 152,
    orderNo: 1,
    deleteF: false,
  },
  {
    categorySeq: 24484,
    kind: "SPENDING",
    name: "IT기기",
    parentSeq: 72,
    orderNo: 6,
    deleteF: false,
  },
  {
    categorySeq: 26981,
    kind: "INCOME",
    name: "추가포인트",
    parentSeq: 45,
    orderNo: 6,
    deleteF: false,
  }
  ],
  codeMain: [{
    codeMainId: "KIND_CODE",
    name: "자산유형",
    deleteF: false,
  },
  {
    codeMainId: "ATTR_SPENDING",
    name: "지출속성",
    deleteF: false,
  },
  {
    codeMainId: "ATTR_TRANSFER",
    name: "이체속성",
    deleteF: false,
  },
  {
    codeMainId: "ATTR_INCOME",
    name: "수입속성",
    deleteF: false,
  },
  {
    codeMainId: "TYPE_STOCK",
    name: "주식종류",
    deleteF: false,
  },
  {
    codeMainId: "TYPE_ACCOUNT",
    name: "계좌성격",
    deleteF: false,
  },
  {
    codeMainId: "TYPE_NATION",
    name: "주식 상장국가",
    deleteF: false,
  }
  ],
  codeItem: [{
    codeMainId: "ATTR_INCOME",
    codeItemSeq: 0,
    name: "단순 수입",
    orderNo: 1,
    deleteF: false,
  },
  {
    codeMainId: "ATTR_INCOME",
    codeItemSeq: 1,
    name: "투자 수입",
    orderNo: 2,
    deleteF: false,
  },
  {
    codeMainId: "ATTR_SPENDING",
    codeItemSeq: 2,
    name: "단순 지출",
    orderNo: 1,
    deleteF: false,
  },
  {
    codeMainId: "ATTR_SPENDING",
    codeItemSeq: 7,
    name: "고정 지출",
    orderNo: 2,
    deleteF: false,
  },
  {
    codeMainId: "ATTR_TRANSFER",
    codeItemSeq: 5,
    name: "단순 이체",
    orderNo: 1,
    deleteF: false,
  },
  {
    codeMainId: "ATTR_TRANSFER",
    codeItemSeq: 6,
    name: "투자 이체",
    orderNo: 2,
    deleteF: false,
  },
  {
    codeMainId: "ATTR_TRANSFER",
    codeItemSeq: 11,
    name: "부채 이체",
    orderNo: 3,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 1,
    name: "신용카드",
    orderNo: 1,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 2,
    name: "체크카드",
    orderNo: 2,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 3,
    name: "은행통장",
    orderNo: 3,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 4,
    name: "정기예금",
    orderNo: 4,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 5,
    name: "정기적금",
    orderNo: 5,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 6,
    name: "주식",
    orderNo: 6,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 7,
    name: "펀드",
    orderNo: 7,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 8,
    name: "받을돈(미수금)",
    orderNo: 8,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 9,
    name: "빌린돈",
    orderNo: 9,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 10,
    name: "보험",
    orderNo: 10,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 11,
    name: "전세보증금",
    orderNo: 11,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 12,
    name: "지갑",
    orderNo: 12,
    deleteF: false,
  },
  {
    codeMainId: "KIND_CODE",
    codeItemSeq: 13,
    name: "포인트",
    orderNo: 13,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_STOCK",
    codeItemSeq: 14,
    name: "개별종목",
    orderNo: 14,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_STOCK",
    codeItemSeq: 15,
    name: "지수 ETF",
    orderNo: 15,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_STOCK",
    codeItemSeq: 16,
    name: "리츠 ETF",
    orderNo: 16,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_STOCK",
    codeItemSeq: 17,
    name: "엑티브 ETF",
    orderNo: 17,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_STOCK",
    codeItemSeq: 18,
    name: "채권 ETF",
    orderNo: 18,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_ACCOUNT",
    codeItemSeq: 19,
    name: "고정자산",
    orderNo: 19,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_ACCOUNT",
    codeItemSeq: 20,
    name: "저축자산",
    orderNo: 20,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_ACCOUNT",
    codeItemSeq: 21,
    name: "투자자산",
    orderNo: 21,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_ACCOUNT",
    codeItemSeq: 22,
    name: "부채자산",
    orderNo: 22,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_NATION",
    codeItemSeq: 23,
    name: "국내",
    orderNo: 23,
    deleteF: false,
  },
  {
    codeMainId: "TYPE_NATION",
    codeItemSeq: 24,
    name: "국내상장 외국 ETF",
    orderNo: 24,
    deleteF: false,
  },
  {
    codeMainId: "미국",
    codeItemSeq: 25,
    name: "국내",
    orderNo: 25,
    deleteF: false,
  }

  ],
  account: [{
    name: "현금",
    accountNumber: "",
    kindCode: 12,
    balance: 0,
    interestRate: "",
    term: "",
    expDate: "",
    monthlyPay: "",
    transferDate: "",
    note: "",
    deleteF: false,
  }],
};